apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: troopers
  labels:
    app: troopers
spec:
  type: NodePort
  ports:
  - port: 5000
    name: troopers
    targetPort: 5000
    nodePort: 30100
  selector:
    app: troopers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: troopers
  name: troopers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troopers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: troopers
    spec:
      containers:
      - name: troopers
        image: ghcr.io/mawinkler/troopers:master
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
